name = "rendr-media"
compatibility_date = "2024-12-29"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.html"

[[pages_build_output_dir]]
value = "dist"